language: node_js
sudo: true
os:
- osx
cache:
  directories:
  - node_modules
  - "/usr/local/Cellar"
node_js:
- '5'
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in .travis/cert.p12.enc -d -a -out ./travis/cert.p12
- "./.travis/add-key.sh"
script:
- npm run lint
- npm run test
- "./build.sh"
env:
  global:
  - secure: KGmmWJO60jaOeLIogqOH88oWTDWBZxXz1hLu3100Y4LeSruaoyV3GzRTIcUrmIdUiceKitFlTO4y1Xxc98fj7aajh2QkF1XpCQ4lz38RtJcjsnUfnDYN93G2hr+NZsCIR+oUYh5/2IfCeiCHoiN+DwCzI6Roao4NIdytTTnFY6REc8R5sxdvsHJqGiiEK5DFqsaG3d8Vx9pXRRwO/8GExOACJZ0h/FuDebvssTalAUK2NLTWFpxQqH8AVu7ofQHexunS24swX6IF+r/hSuExH/oYM8VFTDfCsjmIiQaFrKk+b31a6tuimBWED6ezFxeOL7TEyHfsY7kM4cP5/bUyU2kwDXT7YRPCgjgwMScTRUe2Zm0xWegq4C6m5uuuwEglYklhVBkq3lGAkXjDDQTmVdMXGHtKWg7DIxVjw5tTQNzkJUoauDoz+q3r2EV+rAaNuHWXPZ8uA2Ip4GAidDjjnqiuwxQcG9wy8zFj7V31/TDEfPjRXIoxEAevB2toyXZ2Vxa9/F56SdXCdCl0G7aC+5IT0nRQ3Lz4vjqwwseOGsQk2SVwAJ3QV5as1mBiXjT78rDrTYeTNOWXKeqrsYEyS7A9vmsUZUYOaKEIl4ugOi5tB1GC+qOkJ2FHHXKZaKW/on7CScFXAXeA8eT+DxicukGfauQaNINP6wSciJCpHSE=
  - secure: La8+tLDr/Kb22A/k2M+lpxArsKJIpvX3LesiH2ZEz6vPCkzQ7siRQlRSflP0TuiOvX81WsPzdo1iH544oDl0J2vm5L5hSa/FVYPGEkvOiS1o1of5Pl5ThCzHBWn6Vezz9z3Uvzc31JqkbI0r8mMKePezE2kHH+JkKno/PwTwhfueYBvjVr3s7EYi3Nqo7EcgzvKx6SORsn+Co69idAy4nWURoIyhBb70VsCzIqwOGaSOLdzW5PP7CBrtKmDrlWYdS+Z11y+tcqmTsjJihu5qnfO2ddcC27menx5wbG9N+nD6h+rTzthssRlMeNaqQP/iCGIrPDzMNQXwRH6GxnEmTP++lb5CnYNbkT8hgseJ50mdLJ6oaAY/JSGvXaCVG7t6dmjVKntl5NEbmirs44TusQNX7BGUwDRbl0k4qWaZxNKJp20vMJrKKM32l52vK2DkF7jaQIK5dSuQoY6/EaJPim8VkI6hvn8FhxssmRIxBivUaJukzw2GZQLsEVy9Q372DVcEFIHZwMcQPXAh7K1Cxgs05hAYGO2pYKHSQmQDXZuFxKEZN/zKfsTes0KqZGYEsSj9DkfzcQG8NydSUA55PTPktblMdQ7+JYw4UZUREi/xEhLygYBQUEWvCa0O90iDLucDWDxklN0EH6kKNsTBVsTUiDeUOUG0IRUSqYfSipk=
  - secure: fQ4K2OvSakz0Fk+9X/WWFpPOFoK7IjpI7vAqhEhbH7X2q0iXQUZv1476e3wVQWYlwzks8NlLP4oPXzJm6xooh+1ftxh3q1qlyQlowZKvyqDx/IjOVlZXZoaivqCEwXSmkxH2MG5OL3hjhZr2MG8cai2nbcXPXiUDktGVZm4rJRtbvknPK5TZUMjs9YttvDKy35fa28gdFcXWzKOFerqHIibNzE4CtmAbBhJLgSxopJp3yUrhKhnwEnOA4A3xwFZTARmT02Kfu8y4hOwwylbmysDNT1zWZ9+aNRaB2jvw9DEIevtzcyrmYfTZdbY18nj3O+9Wg8qYPo7YrrSA0pK5NwO9qf5ldxKU4ThfNSMONHgAzZDibXKg9q+axr49PBgNze0YO6T3/ktMIqpP9UPuchrsDMBk54msyqH02drJhQ3FyNLX63Ljt5w20kUks2mQdd/az/NSNGcjH26hDiKUROd7SXTr+cPOOXd0vi/VN1F3AouGVeoaaLm62N0UIv/w+npxn/XDKJE9InHfiGc77KUpysEaA9ydOJ7+WnNSzdGv45pIo87z+/zm6m9yeI/G8IPgo54IHSyLEshLD4azo/egzBkihYPkztX0z2SnMgL9+ph6908R0oy9GV1HgfFzMvwFfR8a4iY/mSkQtaSb5xoAUz1MxxwFel3cQGKXOgU=
